// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgS9KfNF8Hb56_fbszLHCAmSPHKR_1RdM',
    appId: '1:1015468579101:web:6b4ca2805a7ce5eb9429f4',
    messagingSenderId: '1015468579101',
    projectId: 'fitness-app-272eb',
    authDomain: 'fitness-app-272eb.firebaseapp.com',
    storageBucket: 'fitness-app-272eb.firebasestorage.app',
    measurementId: 'G-3J3QSXZF7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsNZ8HgLZSm3Z8VGRE0qZmo-KrPYUK440',
    appId: '1:1015468579101:android:cff7591f033ccfd89429f4',
    messagingSenderId: '1015468579101',
    projectId: 'fitness-app-272eb',
    storageBucket: 'fitness-app-272eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_w4RC3UXE0HMiTL1v0Wb2is4hR8BYT0',
    appId: '1:1015468579101:ios:0361e8d1c1a665849429f4',
    messagingSenderId: '1015468579101',
    projectId: 'fitness-app-272eb',
    storageBucket: 'fitness-app-272eb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_w4RC3UXE0HMiTL1v0Wb2is4hR8BYT0',
    appId: '1:1015468579101:ios:0361e8d1c1a665849429f4',
    messagingSenderId: '1015468579101',
    projectId: 'fitness-app-272eb',
    storageBucket: 'fitness-app-272eb.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgS9KfNF8Hb56_fbszLHCAmSPHKR_1RdM',
    appId: '1:1015468579101:web:79937e257ced88179429f4',
    messagingSenderId: '1015468579101',
    projectId: 'fitness-app-272eb',
    authDomain: 'fitness-app-272eb.firebaseapp.com',
    storageBucket: 'fitness-app-272eb.firebasestorage.app',
    measurementId: 'G-FF33EJSXL0',
  );
}
